[package]
name = "rats-tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foreign-types = "0.5.0"
tokio = { version = "1.19.2", features = ["full"] }
